# Generated by Django 4.1.7 on 2023-02-24 08:37

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('jobType', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Part-time', 'Part Time'), ('Temporary', 'Temporary')], default='Permanent', max_length=30, null=True)),
                ('education', models.CharField(choices=[('High school', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate'), ('Post-doctorate', 'Post Doctorate')], default='Bachelor', max_length=30, null=True)),
                ('experience', models.CharField(choices=[('No Experience', 'No Experience'), ('Less than 1 year', 'Less Than One Year'), ('1 to 3 years', 'One To Three Years'), ('3 to 5 years', 'Three To Five Years'), ('5 to 10 years', 'Five To Ten Years'), ('More than 10 years', 'More Than Ten Years')], default='No Experience', max_length=30, null=True)),
                ('industry', models.CharField(choices=[('Business', 'Business'), ('IT', 'It'), ('Banking', 'Banking'), ('Education/Training', 'Education'), ('Engineering', 'Engineering'), ('Telecommunication', 'Telecommunication'), ('Healthcare', 'Healthcare'), ('Others', 'Others')], default='Others', max_length=30, null=True)),
                ('salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('positions', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=100, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('last_date', models.DateField(default=job.models.return_date_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
