# Generated by Django 4.1.7 on 2023-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_candidateapplied_candidatesapplied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='point',
            new_name='location',
        ),
    ]
