# Generated by Django 4.1.7 on 2023-02-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_created_at_job_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='point',
        ),
    ]
